version: 2.1

orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    working_directory: ~/freecodecamp
    # Reuse Docker container specification
    executor: node/default
    steps:
      - checkout
      # Install the latest npm
      - node/install-npm
      # Install depedencies
      - node/install-packages:
          app-dir: ~/freecodecamp
          cache-path: node_modules
          override-ci-command: npm i
      - run:
          name: Test
          command: npm test
